### ISSUE TITLE
Only Host Can Drop Money: [DoshDrop]

### ISSUE THREAD

**Issue by JamesMDenton** [DestroyedClone/PoseHelper#16] opened 2022-04-05 03:17 UTC
**Describe the bug**
Only the host of the game can drop money. Tested with multiple different hosts, and different hotkeys.

**To Reproduce**
1. Join Multiplayer game as client (NOT host)
2. Press key you have set to drop money.
3. Not profit

**Expected behavior**
Expected to throw money as a client when pressing the throw money hotkey

**Additional context**
Pretty much what it says on the tin.

**Comment by DestroyedClone** [comment] 2022-08-17 20:35
Client doesn't communicate to the host properly to activate the mod, will look into it.

**Comment by DestroyedClone** [comment] 2023-06-29 15:42
Duplicate of https://github.com/DestroyedClone/PoseHelper/issues/14

**Closed by DestroyedClone** 2023-06-29 15:42 UTC
Labels: bug
